CREATE TABLE staging_diabetes (
    encounter_id INT,
    patient_nbr INT,
    race VARCHAR,
    gender VARCHAR,
    age VARCHAR,
    weight VARCHAR,
    admission_type_id INT,
    discharge_disposition_id INT,
    admission_source_id INT,
    time_in_hospital INT,
    payer_code VARCHAR,
    medical_specialty VARCHAR,
    num_lab_procedures INT,
    num_procedures INT,
    num_medications INT,
    number_outpatient INT,
    number_emergency INT,
    number_inpatient INT,
    diag_1 VARCHAR,
    diag_2 VARCHAR,
    diag_3 VARCHAR,
    number_diagnoses INT,
    max_glu_serum VARCHAR,
    A1Cresult VARCHAR,
    metformin VARCHAR,
    repaglinide VARCHAR,
    nateglinide VARCHAR,
    chlorpropamide VARCHAR,
    glimepiride VARCHAR,
    acetohexamide VARCHAR,
    glipizide VARCHAR,
    glyburide VARCHAR,
    tolbutamide VARCHAR,
    pioglitazone VARCHAR,
    rosiglitazone VARCHAR,
    acarbose VARCHAR,
    miglitol VARCHAR,
    troglitazone VARCHAR,
    tolazamide VARCHAR,
    examide VARCHAR,
    citoglipton VARCHAR,
    insulin VARCHAR,
    glyburide_metformin VARCHAR,
    glipizide_metformin VARCHAR,
    glimepiride_pioglitazone VARCHAR,
    metformin_rosiglitazone VARCHAR,
    metformin_pioglitazone VARCHAR,
    change VARCHAR,
    diabetesMed VARCHAR,
    readmitted VARCHAR
);

CREATE TABLE patients (
    patient_id SERIAL PRIMARY KEY,
    patient_nbr INT UNIQUE,
    race VARCHAR,
    gender VARCHAR,
    age_group VARCHAR,
    weight VARCHAR
);

CREATE TABLE encounters (
    encounter_id INT PRIMARY KEY,
    patient_id INT,
    admission_type_id INT,
    discharge_disposition_id INT,
    admission_source_id INT,
    time_in_hospital INT,
    payer_code VARCHAR,
    medical_specialty VARCHAR,
    num_lab_procedures INT,
    num_procedures INT,
    num_medications INT,
    number_outpatient INT,
    number_emergency INT,
    number_inpatient INT,
    diag_1 VARCHAR,
    diag_2 VARCHAR,
    diag_3 VARCHAR,
    number_diagnoses INT,
    max_glu_serum VARCHAR,
    A1Cresult VARCHAR,
    change VARCHAR,
    diabetesMed VARCHAR,
    readmitted VARCHAR,
    CONSTRAINT fk_encounter_patient
        FOREIGN KEY (patient_id)
        REFERENCES patients(patient_id)
);

CREATE TABLE medications (
    encounter_id INT PRIMARY KEY,
    metformin VARCHAR,
    repaglinide VARCHAR,
    nateglinide VARCHAR,
    chlorpropamide VARCHAR,
    glimepiride VARCHAR,
    acetohexamide VARCHAR,
    glipizide VARCHAR,
    glyburide VARCHAR,
    tolbutamide VARCHAR,
    pioglitazone VARCHAR,
    rosiglitazone VARCHAR,
    acarbose VARCHAR,
    miglitol VARCHAR,
    troglitazone VARCHAR,
    tolazamide VARCHAR,
    examide VARCHAR,
    citoglipton VARCHAR,
    insulin VARCHAR,
    glyburide_metformin VARCHAR,
    glipizide_metformin VARCHAR,
    glimepiride_pioglitazone VARCHAR,
    metformin_rosiglitazone VARCHAR,
    metformin_pioglitazone VARCHAR,
    CONSTRAINT fk_medications_encounter
        FOREIGN KEY (encounter_id)
        REFERENCES encounters(encounter_id)
);


